apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users-container
          image: acr96.azurecr.io/users:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "150m"
          env:
            - name: RabbitMQ__HostName
              value: "rabbitmq.messaging.svc.cluster.local"
            - name: RabbitMQ__QueueName
              value: "payments"
            - name: Jwt__Issuer
              valueFrom:
                configMapKeyRef:
                  name: users-config
                  key: JWT_ISSUER
            - name: Jwt__Audience
              valueFrom:
                configMapKeyRef:
                  name: users-config
                  key: JWT_AUDIENCE
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: users-config
                  key: ENVIRONMENT

            - name: ConnectionStrings__TechDb
              valueFrom:
                secretKeyRef:
                  name: users-secrets
                  key: connectionstring
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: users-secrets
                  key: jwtkey
            - name: ElasticSettings__ApiKey
              valueFrom:
                secretKeyRef:
                  name: users-secrets
                  key: elasticapikey
            - name: ElasticSettings__CloudId
              valueFrom:
                secretKeyRef:
                  name: users-secrets
                  key: elasticcloudid
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: users-secrets
                  key: newrelickey
            - name: RabbitMQ__UserName
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: username
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: password
      imagePullSecrets:
        - name: credentials
